### ISSUE TITLE
Searching a way to reselect after a <C-A> / <C-X> like gv

### ISSUE THREAD

**Issue by GuillaumeSeren** [tpope/vim-speeddating#20]
Hi,
I am searching to reselect after increment / decrement like:
vnoremap <C-A> <C-A>gv

This work without speeddating, but I wish to keep speeddating as it is useful to me,
so do you think it is possible to add a hook to do that ?

Thank's for this useful plugin !

Guillaume.

**Comment by GuillaumeSeren** [comment]
I found a workaround and pushed in a branch on my fork here https://github.com/GuillaumeSeren/vim-speeddating/tree/fix-visual-block-reselect
It work well for my case but I can upgrade it if you need.

Would be great to have this feature into speeddating.

**Comment by tpope** [comment]
This should work, no?

    xnoremap <C-A> <Plug>SpeedDatingUpgv

**Comment by GuillaumeSeren** [comment]
Yes exactly what I was searching thank you !
