### ISSUE TITLE
Key bindings do not work

### ISSUE THREAD

**Issue by deshmukhs** [tpope/vim-speeddating#22]
Running Fedora23 KDE spin. KDE Plasma 5.5.5. Qt 5.6.0. Konsole 15.12.3. zsh 5.1.1. vimx 7.4.

Have installed pathogen and SpeedDating using pathogen.

When I do `Ctrl-A`, `Ctrl-X` on a date field, nothing happens.

`:map` shows both `Ctrl-A` and `Ctrl-X` as mappings.

What must be going wrong? How do I set it right?

**Comment by tpope** [comment]
Are you sure the date format in question is supported?

**Comment by deshmukhs** [comment]
My bad.

I did not pay attention to the format. There was an error in the format 
definition. Now it is working fine.

Thanks!

On Tuesday 26 April 2016 02:39 AM, Tim Pope wrote:
>
> Are you sure the date format in question is supported?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/tpope/vim-speeddating/issues/22#issuecomment-214522674>
>

-- 
Regards,
Sandip P Deshmukh
Email: deshmukh.sandip@gmail.com
