### ISSUE TITLE
Fallbacks have no effect

### ISSUE THREAD

**Issue by mickk-on-cpp** [tpope/vim-speeddating#27]
I can’t seem to get Ctrl-A/Ctrl-X to have any effect on regular, non-date numbers in normal mode. I tried disabling nearly every plugin and double-checked that my config is not doing anything to Ctrl-A or Ctrl-X to no avail. I realise that’s not the most helpful of issue reports but I’m at a loss as to what to do next.

The output of `:map <Plug>SpeedDating` looks sensible to me:

```vimL
n  <Plug>SpeedDatingFallbackDown * <C-X>
n  <Plug>SpeedDatingFallbackUp * <C-A>
n  <Plug>SpeedDatingNowUTC * :<C-U>call speeddating#timestamp(1,v:count)<CR>
n  <Plug>SpeedDatingNowLocal * :<C-U>call speeddating#timestamp(0,v:count)<CR>
v  <Plug>SpeedDatingDown * :<C-U>call speeddating#incrementvisual(-v:count1)<CR>
v  <Plug>SpeedDatingUp * :<C-U>call speeddating#incrementvisual(v:count1)<CR>
n  <Plug>SpeedDatingDown * :<C-U>call speeddating#increment(-v:count1)<CR>
n  <Plug>SpeedDatingUp * :<C-U>call speeddating#increment(v:count1)<CR>
```

Same with the output of `:map ^A`:

```vimL
x  <C-A>         <Plug>SpeedDatingUp
n  <C-A>         <Plug>SpeedDatingUp
```

Ditto `:map ^X`, so I’ll omit it.

If I add an `echoerr …` line in `speeddating#increment` right before it executes the fallback dispatch I can see that control flow proceeds as expected [to that point](https://github.com/tpope/vim-speeddating/blob/a418667791f03694065948342f2d6c5cca8d0f32/autoload/speeddating.vim#L105).

The rest of the plugin seems to work fine: I can tweak the example dates provided in the `:help`, do visual increments/decrements, set things to the current date/time, or undo/repeat it all.

**Comment by tpope** [comment]
The next obvious thing to check is `:set nrformats`.

**Comment by mickk-on-cpp** [comment]
I have `nrformats=bin,hex,alpha`.

**Comment by tpope** [comment]
I guess the next step is to try `:exe "norm 1\<Plug>SpeedDatingFallbackUp"` by hand and see what happens.

**Comment by mickk-on-cpp** [comment]
I tried and no effect on the numbers: they are not incremented (nor decremented if I try a `Down` variant), and there’s no new undo state. I tried with the cursor in various places on the following buffer (including on the empty first column):

```text
 10 11 12
 0xABC0 abc
```

What I *did* notice this time that I hadn't paid attention to before is that this always triggers a visual bell, as well as when using the ^X or ^A.

**Comment by tpope** [comment]
Compare to `:exe "norm! \<C-A>"`, I suppose.

**Comment by mickk-on-cpp** [comment]
Yes, this does carry out the increment (ditto decrement for `\<C-X>`).

**Comment by mickk-on-cpp** [comment]
I found it: it’s my own remapping of `1` that I believe makes `:exe "norm 1\<Plug>SpeedDatingFallbackUp"` not perform as intended:

- `:exe \<Plug>SpeedDatingFallbackUp` (no count) behaves as expected
- changing the increment fallback to e.g. `exe "norm \<Plug>SpeedDatingFallbackUp"` also makes the mapping perform as expected (although of course the count no longer has any effect)

**Comment by tpope** [comment]
Yeah I don't see that as worth working around. How do you input `10`?

**Comment by mickk-on-cpp** [comment]
For context I use a keyboard layout which top row has digits accessible on shift, symbols otherwise--the other way around from e.g. QWERTY. I remap for normal mode, such that to input a count I perform the same motions I would on a QWERTY.
