### ISSUE TITLE
More formats

### ISSUE THREAD

**Issue by plexigras** [tpope/vim-speeddating#33]
```
YMD, e.g. 1996-04-22 or 1996.04.22 or 1996/04/22
DMY, e.g. 22.04.1996 or 22/04/1996 or 22-04-1996 or 22 April 1996
MDY, e.g. 04/22/1996 or April 22, 1996
```

https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by tpope** [comment]
Simultaneously supporting both `DMY` and `MDY` is impossible. `YYYY-MM-DD` is already supported. Dots and slashes I very rarely see in the wild but if you want to add support for them knock yourself out.
