### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by MyXelf** [tpope/vim-speeddating#35]
I don't know if your intention is to support Neovim, but there is #23 which addresses one issue i hitted today while migrating to Neovim.

The problem relies on a difference in the `reltime()` function between Neovim and Vim. I can confirm this PR solves the issue with `d<C-X>`. There is no problem with the `d<C-A>` counterpart.

I guess it wouldn't hurt to add to the docs if you have intention to support Neovim.

HTH

**Comment by tpope** [comment]
Okay, merged.
