### ISSUE TITLE
Day name not incremented with date

### ISSUE THREAD

**Issue by unknownbreaker** [tpope/vim-speeddating#37]
When pressing <C-A> over the day number, only the day number increments and not the day name. Same issue if incrementing the month number--day name does not update.

`2020-02-20 Thu 9:04 PM` => `2020-02-24 Thu 9:04 PM`
`2020-02-24 Thu 9:04 PM` => `2020-03-24 Thu 9:04 PM`

**Comment by tpope** [comment]
`2020-02-24 Thu 9:04 PM` isn't a built-in format. Define it with `:SpeedDatingFormat`.

**Comment by j-hui** [comment]
Sorry to open this again, but I have the same issue, after defining it with `:SpeedDatingFormat`.

In my case, I execute:
```
    SpeedDatingFormat %Y-%m-%d %a %H:%M:%S
```

Incrementing the day seems to work when my cursor is over the day name (`%a`), but not when it's over any of the numeric dates.

**Comment by tpope** [comment]
The other formats are taking precedence. Use `:1SpeedDatingFormat` to give it a high priority.

**Comment by j-hui** [comment]
Works excellently, thanks @tpope !
