### ISSUE TITLE
Different date format?

### ISSUE THREAD

**Issue by prankousky** [tpope/vim-speeddating#40]
Hi,

I just stumbled upon this plugin and really like the possibilities it offers. However, it doesn't seem to handle dates like `29.04.2020`, the European format. When I use `2020-04-29` and increase, it will eventually turn to `2020-05-01`; with `29.04.2020`, it will eventually be `33.04.2020`.

Just an idea, because I think lots of people want or need to use this format and would also like to use the plugin :)

Cheers!

**Comment by tpope** [comment]
It's configurable.
