### ISSUE TITLE
Add support for repeat with "."

### ISSUE THREAD

**Issue by strottie** [tpope/vim-speeddating#41]
I often run <count>C-a to increment a number and then use "." to repeat the increment on the same number or a different one. This basic functionality of vim is broken when vim-speeddating is loaded, even if incrementing a simple number.

This issue is to track support for repeating incr/decr action with "."

**Comment by tpope** [comment]
From the README:

> The `.` command will work as expected if you install repeat.vim.

This might be possible to implement without an external dependency by abusing `'operatorfunc'`. I do not have the bandwidth to investigate.
