### ISSUE TITLE
Plans to add a “today” or “now” behavior?

### ISSUE THREAD

**Issue by danielyli** [tpope/vim-speeddating#42]
Hi, are there plans to add a “change this date to today” or “change this timestamp to now” functionality?

E.g.:

* If cursor is on `1999-05-27`, it gets changed to `2021-01-07`
* If cursor is on `1999-05-27T23:42`, it gets changed to `2021-01-07T20:55`.

**Comment by tpope** [comment]
https://github.com/tpope/vim-speeddating/blob/fe98cfaa7ea9c4b838d42a6830437c919eb55b4e/doc/speeddating.txt#L36-L43

**Comment by danielyli** [comment]
Thank you!!
