### ISSUE TITLE
After Friday comes .... Sunday and decreasing from Friday -> Thursday is not working

### ISSUE THREAD

**Issue by jamilraichouni** [tpope/vim-speeddating#45]
Hi!

First many, many thanks for all your cool plugins @tpope .

Now something I experience:

When I

1. create a buffer with just the word `Friday` in it,
2. command `:SpeedDatingFormat %A` (according to #24),
3. place the cursor somewhere in the word `Friday`, and
4. press  Ctrl+A

I get `Sunday`.

I expected `Saturday`.

Is there something I can do so that we have the repeating order

`Monday`
`Tuesday`
`Wednesday`
`Thursday`
`Friday`
`Saturday`
`Sunday`
`Monday`
`Tuesday`
`...`

etc.?

**Comment by jamilraichouni** [comment]
I also see that I cannot decrease from `Friday` to `Thursday` with Ctrl+X.

**Comment by tpope** [comment]
Now that's what I call an old bug!
